name: PR

on: [pull_request]

jobs:
  test-python:
    name: pr-test
    runs-on: ubuntu-latest
    container:
      image: python:3-slim
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
      - run: poetry run flake8 hello.py

