name: Push

on: [push]

env:
  MESSAGE: ${{ vars.MESSAGE }}

jobs:
  test-python:
    name: push-test
    runs-on: ubuntu-latest
    container:
      image: python:3-slim
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
      - run: poetry run flake8 hello.py
  greetings:
    name: push-greeting
    runs-on: ${{ vars.UBUNTU_LATEST }}
    container:
      image: ${{ vars.ALPINE_IMAGE }}
    steps:
      - run: echo "$MESSAGE"

